In [1]:
import sys
import os

print("Python executable:", sys.executable)
print("Python version:", sys.version)
print("Major.Minor:", f"{sys.version_info.major}.{sys.version_info.minor}")
print("Current working directory:", os.getcwd())

Python executable: C:\Users\mohdk\anaconda3\python.exe
Python version: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
Major.Minor: 3.11
Current working directory: C:\Users\mohdk\AI Communication Insights Engine\notebooks

In [1]:
import numpy
import sklearn
import hdbscan
import umap
from sentence_transformers import SentenceTransformer

print("numpy:", numpy.__version__)
print("sklearn:", sklearn.__version__)
print("Imports successful")

numpy: 1.26.4
sklearn: 1.6.1
Imports successful

In [2]:
import os

raw_data_path = "../data/raw"

print("Raw data path exists:", os.path.exists(raw_data_path))
print("\nContents of raw folder:")

for item in os.listdir(raw_data_path):
    item_path = os.path.join(raw_data_path, item)
    if os.path.isfile(item_path):
        print(f"FILE   : {item}")
    elif os.path.isdir(item_path):
        print(f"FOLDER : {item}")

Raw data path exists: True

Contents of raw folder:
FILE   : emails.csv

In [3]:


raw_data_path = "../data/raw"

print("Walking through first level of dataset structure:\n")

for root, dirs, files in os.walk(raw_data_path):
    print(f"Current folder: {root}")
    print(f"Subfolders: {dirs[:5]}")
    print(f"Files: {files[:5]}")
    print("-" * 60)
    
    # stop after a few levels so output doesn't get crazy
    if root.count(os.sep) - raw_data_path.count(os.sep) >= 2:
        break

Walking through first level of dataset structure:

Current folder: ../data/raw
Subfolders: []
Files: ['emails.csv']
------------------------------------------------------------

In [4]:
import pandas as pd

file_path = "../data/raw/emails.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully.\n")

print("Shape of dataset:")
print(df.shape)

print("\nColumn names:")
print(df.columns)

print("\nFirst 5 rows:")
display(df.head())

Dataset loaded successfully.

Shape of dataset:
(517401, 2)

Column names:
Index(['file', 'message'], dtype='object')

First 5 rows:

                       file                                            message
0     allen-p/_sent_mail/1.  Message-ID: <18782981.1075855378110.JavaMail.e...
1    allen-p/_sent_mail/10.  Message-ID: <15464986.1075855378456.JavaMail.e...
2   allen-p/_sent_mail/100.  Message-ID: <24216240.1075855687451.JavaMail.e...
3  allen-p/_sent_mail/1000.  Message-ID: <13505866.1075863688222.JavaMail.e...
4  allen-p/_sent_mail/1001.  Message-ID: <30922949.1075863688243.JavaMail.e...

In [5]:
print("Data types:\n")
print(df.dtypes)

print("\nMissing values per column:\n")
print(df.isnull().sum())

Data types:

file       object
message    object
dtype: object

Missing values per column:

file       0
message    0
dtype: int64

In [6]:
df["message_length"] = df["message"].astype(str).apply(len)

print("Message length statistics:\n")
print(df["message_length"].describe())

Message length statistics:

count    5.174010e+05
mean     2.719685e+03
std      8.360329e+03
min      3.830000e+02
25%      9.020000e+02
50%      1.529000e+03
75%      2.698000e+03
max      2.011941e+06
Name: message_length, dtype: float64

In [11]:
print(df["message"].iloc[1])

Message-ID: <15464986.1075855378456.JavaMail.evans@thyme>
Date: Fri, 4 May 2001 13:51:00 -0700 (PDT)
From: phillip.allen@enron.com
To: john.lavorato@enron.com
Subject: Re:
Mime-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit
X-From: Phillip K Allen
X-To: John J Lavorato <John J Lavorato/ENRON@enronXgate@ENRON>
X-cc:
X-bcc:
X-Folder: \Phillip_Allen_Jan2002_1\Allen, Phillip K.\'Sent Mail
X-Origin: Allen-P
X-FileName: pallen (Non-Privileged).pst

Traveling to have a business meeting takes the fun out of the trip.  Especially if you have to prepare a presentation.  I would suggest holding the business plan meetings here then take a trip without any formal business meetings.  I would even try and get some honest opinions on whether a trip is even desired or necessary.

As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about what is working and what is not.  Too often the presenter speaks and the others are quiet just waiting for their turn.   The meetings might be better if held in a round table discussion format.

My suggestion for where to go is Austin.  Play golf and rent a ski boat and jet ski's.  Flying somewhere takes too much time.

In [18]:
import re

def parse_email(raw_email):
    
    parts = raw_email.split("\n\n", 1)
    headers = parts[0]
    body = parts[1] if len(parts) > 1 else ""
    
    sender = None
    recipients = None
    date = None
    subject = ""
    
    for line in headers.split("\n"):
        
        if line.startswith("From:"):
            sender = line.replace("From:", "").strip()
            
        elif line.startswith("To:"):
            recipients = line.replace("To:", "").strip()
            
        elif line.startswith("Date:"):
            date = line.replace("Date:", "").strip()
            
        elif line.startswith("Subject:"):
            subject = line.replace("Subject:", "").strip()
    
    return {
        "sender": sender,
        "recipients": recipients,
        "date": date,
        "subject": subject,
        "body": body.strip()
    }

In [19]:
parsed_email = parse_email(df["message"].iloc[0])

parsed_email

{'sender': 'phillip.allen@enron.com',
 'recipients': 'tim.belden@enron.com',
 'date': 'Mon, 14 May 2001 16:39:00 -0700 (PDT)',
 'subject': '',
 'body': 'Here is our forecast'}

In [24]:
parsed_email = parse_email(df["message"].iloc[0])
parsed_email

{'sender': 'phillip.allen@enron.com',
 'recipients': 'tim.belden@enron.com',
 'date': 'Mon, 14 May 2001 16:39:00 -0700 (PDT)',
 'subject': '',
 'body': 'Here is our forecast'}

In [25]:
parsed_data = df["message"].apply(parse_email)

parsed_df = pd.DataFrame(parsed_data.tolist())

print("Parsed dataframe shape:")
print(parsed_df.shape)

print("\nParsed dataframe columns:")
print(parsed_df.columns)

print("\nFirst 5 parsed rows:")
display(parsed_df.head())

Parsed dataframe shape:
(517401, 5)

Parsed dataframe columns:
Index(['sender', 'recipients', 'date', 'subject', 'body'], dtype='object')

First 5 parsed rows:

,sender,recipients,date,subject,body
0,phillip.allen@enron.com,tim.belden@enron.com,"Mon, 14 May 2001 16:39:00 -0700 (PDT)",,Here is our forecast
1,phillip.allen@enron.com,john.lavorato@enron.com,"Fri, 4 May 2001 13:51:00 -0700 (PDT)",Re:,Traveling to have a business meeting takes the...
2,phillip.allen@enron.com,leah.arsdall@enron.com,"Wed, 18 Oct 2000 03:00:00 -0700 (PDT)",Re: test,test successful. way to go!!!
3,phillip.allen@enron.com,randall.gay@enron.com,"Mon, 23 Oct 2000 06:13:00 -0700 (PDT)",,"Randy,\n\n Can you send me a schedule of the s..."
4,phillip.allen@enron.com,greg.piper@enron.com,"Thu, 31 Aug 2000 05:07:00 -0700 (PDT)",Re: Hello,Let's shoot for Tuesday at 11:45.

In [26]:
structured_df = pd.concat([df[["file"]], parsed_df], axis=1)

print("Structured dataframe shape:")
print(structured_df.shape)

display(structured_df.head())

Structured dataframe shape:
(517401, 6)

,file,sender,recipients,date,subject,body
0,allen-p/_sent_mail/1.,phillip.allen@enron.com,tim.belden@enron.com,"Mon, 14 May 2001 16:39:00 -0700 (PDT)",,Here is our forecast
1,allen-p/_sent_mail/10.,phillip.allen@enron.com,john.lavorato@enron.com,"Fri, 4 May 2001 13:51:00 -0700 (PDT)",Re:,Traveling to have a business meeting takes the...
2,allen-p/_sent_mail/100.,phillip.allen@enron.com,leah.arsdall@enron.com,"Wed, 18 Oct 2000 03:00:00 -0700 (PDT)",Re: test,test successful. way to go!!!
3,allen-p/_sent_mail/1000.,phillip.allen@enron.com,randall.gay@enron.com,"Mon, 23 Oct 2000 06:13:00 -0700 (PDT)",,"Randy,\n\n Can you send me a schedule of the s..."
4,allen-p/_sent_mail/1001.,phillip.allen@enron.com,greg.piper@enron.com,"Thu, 31 Aug 2000 05:07:00 -0700 (PDT)",Re: Hello,Let's shoot for Tuesday at 11:45.

In [27]:
output_path = "../data/processed/structured_emails.csv"
structured_df.to_csv(output_path, index=False)

print(f"Saved structured dataset to: {output_path}")

Saved structured dataset to: ../data/processed/structured_emails.csv

In [28]:
print("Missing values per column:\n")
print(structured_df.isnull().sum())

print("\nEmpty sender count:")
print((structured_df["sender"].astype(str).str.strip() == "").sum())

print("\nEmpty recipients count:")
print((structured_df["recipients"].astype(str).str.strip() == "").sum())

print("\nEmpty date count:")
print((structured_df["date"].astype(str).str.strip() == "").sum())

print("\nEmpty subject count:")
print((structured_df["subject"].astype(str).str.strip() == "").sum())

print("\nEmpty body count:")
print((structured_df["body"].astype(str).str.strip() == "").sum())

Missing values per column:

file              0
sender            0
recipients    21847
date              0
subject           0
body              0
dtype: int64

Empty sender count:
0

Empty recipients count:
580

Empty date count:
0

Empty subject count:
19187

Empty body count:
0

In [29]:
print("Duplicate full rows:")
print(structured_df.duplicated().sum())

print("\nDuplicate message bodies only:")
print(structured_df["body"].duplicated().sum())

print("\nDuplicate file paths:")
print(structured_df["file"].duplicated().sum())

Duplicate full rows:
0

Duplicate message bodies only:
269529

Duplicate file paths:
0

In [30]:
structured_df["body_length"] = structured_df["body"].astype(str).apply(len)

print(structured_df["body_length"].describe())

count    5.174010e+05
mean     1.842764e+03
std      8.179131e+03
min      1.000000e+00
25%      2.870000e+02
50%      7.680000e+02
75%      1.753000e+03
max      2.011422e+06
Name: body_length, dtype: float64

In [31]:
short_emails = structured_df[structured_df["body_length"] < 50]

print("Emails with body < 50 characters:")
print(len(short_emails))

Emails with body < 50 characters:
21791

In [32]:
short_emails[["subject", "body"]].head(10)

,subject,body
0,,Here is our forecast
2,Re: test,test successful. way to go!!!
4,Re: Hello,Let's shoot for Tuesday at 11:45.
7,Re: PRC review - phone calls,any morning between 10 and 11:30
15,Re: 2001 Margin Plan,"Paula,\n\n 35 million is fine\n\nPhillip"
43,,"Jeff,\n\n What is up with Burnet?\n\nPhillip"
65,Re:,resumes of whom?
76,Re: Security Request: CLOG-4NNJEZ has been Den...,Why are his requests coming to me?
90,Re: ENA Fileplan Project - Needs your approval,you have my approval
107,Re: Ad Hoc VaR model,I tried to run the model and it did not work

In [33]:
import re

def clean_email_body(text):
    
    if pd.isna(text):
        return ""
    
    # remove line breaks
    text = text.replace("\n", " ")
    
    # remove multiple spaces
    text = re.sub(r"\s+", " ", text)
    
    # remove leading/trailing spaces
    text = text.strip()
    
    return text

In [34]:
structured_df["clean_body"] = structured_df["body"].apply(clean_email_body)

structured_df[["body", "clean_body"]].head(5)

,body,clean_body
0,Here is our forecast,Here is our forecast
1,Traveling to have a business meeting takes the...,Traveling to have a business meeting takes the...
2,test successful. way to go!!!,test successful. way to go!!!
3,"Randy,\n\n Can you send me a schedule of the s...","Randy, Can you send me a schedule of the salar..."
4,Let's shoot for Tuesday at 11:45.,Let's shoot for Tuesday at 11:45.

In [35]:
structured_df[["body", "clean_body"]].head()

,body,clean_body
0,Here is our forecast,Here is our forecast
1,Traveling to have a business meeting takes the...,Traveling to have a business meeting takes the...
2,test successful. way to go!!!,test successful. way to go!!!
3,"Randy,\n\n Can you send me a schedule of the s...","Randy, Can you send me a schedule of the salar..."
4,Let's shoot for Tuesday at 11:45.,Let's shoot for Tuesday at 11:45.

In [47]:
def remove_email_threads(text):
    
    if pd.isna(text):
        return ""
    
    separators = [
        "-----Original Message-----",
        "----- Forwarded by",
        "From: ",
        "Sent: ",
        "To: ",
        "Subject: "
    ]
    
    for sep in separators:
        if sep in text:
            text = text.split(sep)[0]
    
    return text.strip()

In [48]:
structured_df["clean_body"] = structured_df["clean_body"].apply(remove_email_threads)

In [62]:
structured_df[["clean_body"]].sample(20)

                                               clean_body
114652  Until further, it is best to avoid long positi...
244285  <<...OLE_Obj...>> National Association of Manu...
132943  Who do I call to get my palm hooked up to my c...
362545  Confirm # 343360 50MMbut per month for 10/2000...
174633  Interstates Not Welcome in SoCal Territory Cal...
385801  I have reviewed Chris' version of the Confirma...
148323  Start Date: 4/11/01; HourAhead hour: 14; No an...
86688   I have discussed with Doug Gilbert-Smith the t...
337650  Start Date: 1/28/02; HourAhead hour: 23; No an...
59010   Carolyn Kepplinger (sp?) is calling me no doub...
274869  no thanks. superbowl sunday is a big day for m...
150477  Guz- thought you might appreciate this. See yo...
183388  Please be advised, I am planning to take the w...
171341
188775  Please distribute the revised index to the abo...
440825  I talked to Louise and she said that Mark Tayl...
291338
12987   Fantasy Basketball is here...and it's FREE! Jo...
459526  Geoff, Attached is yesterdays NG curves that g...
428609  Sorry to have to respond via e-mail but I've g...

In [53]:
import re
import pandas as pd

def normalize_email_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    
    # remove image placeholders
    text = re.sub(r"\[IMAGE\]", " ", text, flags=re.IGNORECASE)
    
    # remove long runs of dashes, underscores, equals
    text = re.sub(r"[-_=]{3,}", " ", text)
    
    # remove common forwarded/original markers left in body
    text = re.sub(r"\bOriginal Message\b", " ", text, flags=re.IGNORECASE)
    text = re.sub(r"\bForwarded by\b.*", " ", text, flags=re.IGNORECASE)
    
    # remove excessive punctuation spacing
    text = re.sub(r"\s+", " ", text)
    
    # strip whitespace
    text = text.strip()
    
    return text

In [54]:
structured_df["clean_body"] = structured_df["clean_body"].apply(normalize_email_text)

In [67]:
structured_df[["clean_body"]].sample(20)

                                               clean_body
247628
394090          Attached is the weekly litigation report.
241529  Sue Mara Enron Corp. Tel: (415) 782-7802 Fax:(...
378400
234167
145942  Start Date: 2/28/01; HourAhead hour: 8; No anc...
266606  Wes is going to tell me in the morning if he i...
404885  You crack me up. I was going to email you toda...
370061  Many thanks. Your copy works like a charm. I'l...
33312   Joe, Can I have a break-down of just the chang...
461197  that's not our house for sale yet, but probabl...
306297  Yes, but let me review it before anyone else s...
206609  Vince, Here is my list of collected materials....
137317
73070   Hope everyone had a wonderful Thanksgiving hol...
262527  Just a note to let you know that CBS SportLine...
373571  EFF_DT PORTFOLIO_ID DOWN95 12/29/00 MANAGEMENT...
197063  When are you coming in? When shall we have din...
355850  All documentation has been executed and delive...
129115  COLUMBIA GAS TRANSMISSION CORPORATION NOTICE T...

In [68]:
import re
import pandas as pd

def classify_email_relevance(text):
    """
    Classify emails into:
    - keep
    - review
    - drop
    
    This is a first-pass heuristic filter.
    We are not aiming for perfection here.
    """
    
    if pd.isna(text):
        return "drop"
    
    text = str(text).strip()
    lower_text = text.lower()
    
    # 1. Empty or near-empty
    if text == "":
        return "drop"
    
    # 2. Very short low-information messages
    low_info_phrases = {
        "thanks", "thank you", "ok", "okay", "yes", "no", "done",
        "noted", "fine", "great", "sure", "approved"
    }
    if lower_text in low_info_phrases:
        return "drop"
    
    # 3. URL-only or mostly URL
    if re.fullmatch(r"https?://\S+", text):
        return "drop"
    
    # 4. Attachment / placeholder style text
    if re.search(r"<<.*?\.(zip|xls|xlsx|doc|docx|pdf|ppt|pptx)>>", text, flags=re.IGNORECASE):
        return "review"
    
    # 5. System/template style patterns
    if re.search(r"start date:.*hourahead hour:", lower_text):
        return "drop"
    
    if re.search(r"username:|password:|host code|electronic tr", lower_text):
        return "drop"
    
    # 6. Pure contact-card / signature-like rows
    if re.search(r"tel:|fax:|phone:|mobile:", lower_text) and len(text.split()) < 15:
        return "drop"
    
    # 7. Extremely short rows
    word_count = len(text.split())
    if word_count <= 2:
        return "drop"
    
    # 8. Small but maybe meaningful rows
    if 3 <= word_count <= 5:
        return "review"
    
    # 9. Suspicious placeholder / separator leftovers
    if re.fullmatch(r"[-_= .]+", text):
        return "drop"
    
    # 10. Default keep
    return "keep"

In [69]:
structured_df["relevance_label"] = structured_df["clean_body"].apply(classify_email_relevance)

In [70]:
print(structured_df["relevance_label"].value_counts(dropna=False))

relevance_label
keep      417911
drop       75054
review     24436
Name: count, dtype: int64

In [71]:
print("\nKEEP samples:")
display(structured_df.loc[structured_df["relevance_label"] == "keep", ["clean_body"]].sample(10, random_state=42))

print("\nREVIEW samples:")
display(structured_df.loc[structured_df["relevance_label"] == "review", ["clean_body"]].sample(10, random_state=42))

print("\nDROP samples:")
display(structured_df.loc[structured_df["relevance_label"] == "drop", ["clean_body"]].sample(10, random_state=42))

KEEP samples:

                                               clean_body
294879  According to the letters rec'd from Legal, app...
404088  CONGRATULATIONS!!! PAT JOHNSON is the winner f...
32647   Please plan on attending a meeting Monday, Feb...
23507   Congratulations! I am very pleased for your co...
506976  W E E K E N D S Y S T E M S A V A I L A B I L ...
86487   Hey there! How are things down in Houston? I c...
404165  Hello everyone! I would love to have dinner an...
183863  Attached is a Canadian Credit Watch listing. I...
82794   You did an absolutely fabulous job on Sunday. ...
363663                    John, Thank you very much Vladi

REVIEW samples:

                                               clean_body
340388                           Hi Dexter! Here you are!
279683                       Anytime after 4:00 PM. -Andy
267217                                  Looks good to me.
328737                                        Dan, FYI. m
333235                                Thanks a lot. Errol
423561                                   For your review.
39778                          Any thoughts on this? Rick
68057                           Inline attachment follows
9097                           meeting with John Lavorato
284924  NESA / HEA 2nd Annual Charity Golf Tournament ...

DROP samples:

                                               clean_body
282646  Start Date: 4/26/01; HourAhead hour: 7; No anc...
222703
327046
470914  Attention POWER REPORT Readers: Go to http://w...
166239
458530
49093                                                 fyi
270816
242295
505667

In [72]:
analysis_df = structured_df[
    structured_df["relevance_label"].isin(["keep", "review"])
].copy()

print("Final analysis dataset shape:")
print(analysis_df.shape)

Final analysis dataset shape:
(442347, 9)

In [76]:
analysis_df[["clean_body"]].sample(20)

                                               clean_body
280210  =09 =09 =09 =09 =09 Upgrades DownGrades= Cover...
174156                    You won't believe your eyes....
146728  This is just a reminder that all 360 feedback ...
178921  Kevin, As we discussed, here are the changes I...
464143  Prebon is sending a new confirmation with Cons...
419990        Susan will be in around 9:30 - 10:00 today.
262475  I will be out of the office Wednesday 11/21/01...
40427   PG&E Fights Toxin in Gas Stream, Movie Fallout...
373516  I was trying to tell you that the blonde chick...
289754  Effective 10-26-2000 please change the primary...
307256  I had a brief conversation with Herman Manis, ...
402279                             more :) - Far_side.jpg
312589  Fred, Dale Rasmussen has been handling the bre...
346887  Ken, I am forwarding the initialed cover lette...
21189   Please put my name on the list to attend this ...
480098                         Great idea -- It's done. >
116409                               pls print. thanks df
204743  Michele, I have defined the project for the st...
220758  I am teaching a class at Rice and one of my ve...
35248   CALENDAR ENTRY: APPOINTMENT Description: John ...

In [78]:
analysis_df.shape

(442347, 9)

In [79]:
pilot_df = analysis_df.sample(n=20000, random_state=42).copy()

print("Pilot dataset shape:")
print(pilot_df.shape)

pilot_df[["clean_body"]].sample(10, random_state=42)

Pilot dataset shape:
(20000, 9)

                                               clean_body
463703  April 1. Thanks for all your help. Kate Symes ...
492565  I need everyone to close out of Lotus Notes an...
328345  Jeff, FYI and consideration, here is another s...
277153  how is your face doing? is the swelling going ...
95152   Given the evolution of a number of our busines...
261884  and the current slides you have on display I'l...
232513  Thanks for the update. Congratulations on your...
483197  If the PA and ETA are still structured as they...
230597                           Look good at this stage.
188951  As and when complete, please prepare a listing...

In [80]:
print("Duplicate clean_body rows in analysis_df:")
print(analysis_df["clean_body"].duplicated().sum())

print("\nDuplicate clean_body rows in pilot_df:")
print(pilot_df["clean_body"].duplicated().sum())

Duplicate clean_body rows in analysis_df:
233578

Duplicate clean_body rows in pilot_df:
1313

In [81]:
pilot_df = pilot_df.drop_duplicates(subset="clean_body").copy()

print("Pilot dataset after removing duplicates:")
print(pilot_df.shape)

Pilot dataset after removing duplicates:
(18687, 9)

In [82]:
pilot_df[["clean_body"]].sample(10, random_state=42)

                                               clean_body
122275  We'll do >>> Geaccone, Tracy 10/12/01 12:14PM ...
344407  Per Scott Josey, the Crescendo Status meeting ...
262082  I have an open order that was placed on 1/2/01...
3585    i have a very pretty back of the head cash wen...
346533  Hi Gerald: ENA has 2 executed agreements with ...
500261  she was encouraged to talk w/you after meeting...
257848  My apoligies for the confusion. Please call me...
230680  attached is a notice from CERA re California b...
508751  Jason, For gas day May 3rd, Peoples delivery f...
502019  Following please find the Daily EnronOnline Ex...

In [83]:
import re

def alpha_ratio(text):
    if not isinstance(text, str):
        return 0
    
    letters = len(re.findall(r"[A-Za-z]", text))
    total = len(text)
    
    if total == 0:
        return 0
    
    return letters / total

pilot_df["alpha_ratio"] = pilot_df["clean_body"].apply(alpha_ratio)

pilot_df["alpha_ratio"].describe()

count    18687.000000
mean         0.744605
std          0.077516
min          0.000000
25%          0.719710
50%          0.767045
75%          0.792879
max          0.920000
Name: alpha_ratio, dtype: float64

In [84]:
pilot_df[pilot_df["alpha_ratio"] < 0.4][["clean_body"]].sample(20, random_state=42)

                                               clean_body
262790                 Effective 1/1/2001 . . . . . . . .
98708   Please provide me with your basis offer for th...
51539   Pulpex Bulletin for Wednesday, November 28, 20...
245823  Attached is some spending to date by the CDWR....
297559  - 02_1.jpg - 02_2.jpg - 02_3.jpg - 02_4.jpg - ...
102074  Here are the days I have discrepancies with PG...
79932                     no. call me. 415.505.6633. jeff
7543                                     2.75 ... but yea
452564  Carol St. Clair EB 3892 713-853-3989 (Phone) 7...
507297  Valuation Date: 12/31/2002 Jun-03 Jun-04 Jun-0...
112129  O'Neal, The following volume changes were made...
488196                             PJM Oasis 610-666-8972
87563   Desk Short Term Northwest Short Term Californi...
515853  Natural Gas Straddles Month Strike Bid Offer V...
58316               Date: Thu, 17 May 2001 11:44:56 -0500
15297   Here's the schedule: 10/3 9 10/10 bye 10/17 6 ...
300930                                             2 of 2
344129                              AGA for 7/28/00 is 63
137568  NQ2167.1 NQ2177.1 NQ4558.1 NQ4558.4 NS7295.1 N...
160414  Please see attached. - EL01-51.1 - ER011489.1 ...

In [85]:
print("Rows removed if threshold = 0.2")
print((pilot_df["alpha_ratio"] < 0.2).sum())

print("\nRows removed if threshold = 0.4")
print((pilot_df["alpha_ratio"] < 0.4).sum())

Rows removed if threshold = 0.2
11

Rows removed if threshold = 0.4
91

In [86]:
pilot_df[pilot_df["alpha_ratio"] < 0.4][["clean_body"]].sample(20)

                                               clean_body
51539   Pulpex Bulletin for Wednesday, November 28, 20...
245823  Attached is some spending to date by the CDWR....
129539                $4.275 by $4.295 at 1"07pm on amtel
273641            lists@nbr.org on 03/21/2001 04:02:46 PM
51278   Pulpex Bulletin for Wednesday, November 21, 20...
324077  = = = = = = = = = = = = = = = = = = Interconti...
437159                                 7138533407 Rick S.
464552  http://www.p1800.com/cars.htm \\\|/// \\ - - /...
308139  May 25, 2001 $1,352,197 June 25, 2001 1,159,02...
92065   Arthur A. Cohen 202-371-7892 (W) 202-371-7896 ...
224537  Aram Sogomonian Phone: (503) 813 5754 (w) 5608...
341601                              AGA for 11/3/00 is 36
241608  =09Richard Shapiro =0902/21/2001 04:51 PM =09=...
140121  3-9573 281-304-8303 832-563-6328 N/A Enron Nor...
158267              Date: Mon, 19 Mar 2001 08:25:49 -0600
108349  Decrease Entex ROM 142509 dth by 6 days = 855,...
344115                             AGA for 10/27/00 is 70
515411         770-933-9522 ext. 134770-933-9522 ext. 134
124930                               now $4.085 by $4.095
134913  k# MDQ 892510 16136 Access to M3 892511 7426 A...

In [87]:
pilot_df = pilot_df[pilot_df["alpha_ratio"] >= 0.4].copy()

print("Final pilot dataset shape:")
print(pilot_df.shape)

Final pilot dataset shape:
(18596, 10)

In [88]:
pilot_df = pilot_df.reset_index(drop=True)

In [89]:
texts = pilot_df["clean_body"].tolist()

print("Number of texts:", len(texts))
print("\nExample text:")
print(texts[0])

Number of texts: 18596

Example text:
Due to the current business circumstances the hours to the Energizer Cafe, The Express Store, and Plaza Java will be adjusted as of Monday, December 10, 2001. Please note the operating hours for each location below: Energizer Cafe Breakfast: 7:30 to 9:00 AM Lunch: 11:30 AM to 1:00 PM The Express Store 8:30 AM to 3:00 PM Plaza Java 7:00 AM to 3:00 PM Thank you.

In [90]:
pilot_df.shape

(18596, 10)

In [91]:
pilot_df["word_count"] = pilot_df["clean_body"].apply(lambda x: len(x.split()))

pilot_df["word_count"].describe()

count    18596.000000
mean       162.006668
std        937.480700
min          3.000000
25%         18.000000
50%         42.000000
75%        108.000000
max      62524.000000
Name: word_count, dtype: float64

In [92]:
pilot_df.sort_values("word_count", ascending=False)[["clean_body","word_count"]].head(10)

                                              clean_body  word_count
9221   <OMNI> <OMNINotes></OMNINotes> <OMNIPAB>PERSON...       62524
8901   Wall Street Journal, June 4, 2001, California ...       34777
4196   Today's News....Thanks - Jean Wall Street Jour...       32754
1954   Please see the following articles: Sac Bee, Tu...       30168
41     Please see the following articles: AP Wire ser...       26972
13978  **Please check the front page of today's issue...       24905
4586   Please see the following articles: Sac Bee, We...       23616
8958   Please see the following articles: Sac Bee, Th...       22761
4309   Enron Discusses Credit Line of $1 Billion to $...       20684
17482  Please see the following articles: Sac Bee, We...       19186

In [93]:
pilot_df.sort_values("word_count")[["clean_body","word_count"]].head(10)

                      clean_body  word_count
11192   MBA salaries, tuition...           3
1859                Good idea. m           3
13654      get transmission done           3
10530       Donna, Thanks. Vince           3
13011    This is interesting....           3
16556           Hi Robin, Voila.           3
14888  Forgot the attachment....           3
8487                   FYI - SRS           3
1137           have we reponded?           3
9647             FYI Jim Derrick           3

In [94]:
pilot_df = pilot_df[pilot_df["word_count"] <= 1000].copy()

print("Pilot dataset after removing newsletters:")
print(pilot_df.shape)

Pilot dataset after removing newsletters:
(18186, 11)

In [95]:
pilot_df.sort_values("word_count", ascending=False)[["clean_body","word_count"]].head(10)

                                              clean_body  word_count
14616  =3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=3D=...         998
17546  CAN NEW YORK AVOID CALIFORNIA'S BLACKOUTS? Mon...         998
16893  Charles Schwab & Co., Inc. Morning Market View...         994
3114   Morning Report for Tuesday, June 6, 2001 http:...         992
7073   Rogers, Enron Energy Services, Inc. ("EESI") s...         989
9792   =09 =09 =09 =09 =09 =09 =09[IMAG= E]=09 Tips &...         988
249    B R E A K F A S T W I T H T H E F O O L Monday...         984
9705   High Prices Force Chemicals to Sell Gas, Futur...         981
2256   There are several items worth noting regarding...         981
5571   Energy Boost Electricity generators note Bush'...         981

In [96]:
pilot_df.shape

(18186, 11)

In [97]:
import re

def remove_encoding_artifacts(text):
    
    if not isinstance(text, str):
        return ""
    
    # remove patterns like =3D, =09 etc.
    text = re.sub(r"=[0-9A-F]{2}", " ", text)
    
    # remove long repeated equals signs
    text = re.sub(r"={2,}", " ", text)
    
    # normalize whitespace
    text = re.sub(r"\s+", " ", text)
    
    return text.strip()

In [98]:
pilot_df["clean_body"] = pilot_df["clean_body"].apply(remove_encoding_artifacts)

In [99]:
pilot_df.sort_values("word_count", ascending=False)[["clean_body","word_count"]].head(5)

                                              clean_body  word_count
14616  = = As requested, your News Alert for JDSU fol...         998
17546  CAN NEW YORK AVOID CALIFORNIA'S BLACKOUTS? Mon...         998
16893  Charles Schwab & Co., Inc. Morning Market View...         994
3114   Morning Report for Tuesday, June 6, 2001 http:...         992
7073   Rogers, Enron Energy Services, Inc. ("EESI") s...         989

In [114]:
pilot_df[["clean_body"]].sample(20)

                                              clean_body
14532  Please see attached for the most up to date ve...
14202  Thanks Laurie. We have this on our "To Do" lis...
4083   The Raiders have always been my team. The Char...
947         is this going to be the buying op for apple?
896    HI Everyone, As you know, we now have two roun...
179       (See attached file: hpl0920.xls) - hpl0920.xls
8951   EFF_DT PORTFOLIO_ID DOWN95 2/12/01 MANAGEMENT-...
1066   Can you please help me to resolve this ASAP. T...
11457       what is the current head count on this trip?
17569  <<Override Letter for LV Cogen Turbine Agreeme...
16637                the phone number in 30C1 is x37320.
6325                  see you at the freight. best, jeff
1384   Thanks. Many of the changes to Brian's CO don'...
570    Please see attached memo. The Court of Appeal ...
18254  Here are the times for the meetings with Finan...
3054   L. Burgess 221 NW 2nd Street Corvallis, OR 973...
8799   Kim, Please disregard previous draft for C of ...
3498   here is the spreadsheet that you sent. Please ...
15358  Thanks, Tana. Hope you're feeling better.........
4329   Here is a new copy of the El Paso capacity she...

In [115]:
!pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-5.2.3-py3-none-any.whl.metadata (16 kB)
Collecting transformers<6.0.0,>=4.41.0 (from sentence-transformers)
  Downloading transformers-5.3.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub>=0.20.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: torch>=1.11.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: numpy in C:\Users\mohdk\anaconda3\Lib\site-packages (from sentence-transformers) (1.26.4)
Requirement already satisfied: scikit-learn in C:\Users\mohdk\anaconda3\Lib\site-packages (from sentence-transformers) (1.2.2)
Requirement already satisfied: scipy in C:\Users\mohdk\anaconda3\Lib\site-packages (from sentence-transformers) (1.11.4)
Requirement already satisfied: typing_extensions>=4.5.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm in C:\Users\mohdk\anaconda3\Lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\mohdk\anaconda3\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in C:\Users\mohdk\anaconda3\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2023.10.3)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in C:\Users\mohdk\anaconda3\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Collecting safetensors>=0.4.3 (from transformers<6.0.0,>=4.41.0->sentence-transformers)
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2023.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in C:\Users\mohdk\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.2.0)
Requirement already satisfied: certifi in C:\Users\mohdk\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\mohdk\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\mohdk\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.4)
Requirement already satisfied: h11>=0.16 in C:\Users\mohdk\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\mohdk\anaconda3\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\mohdk\anaconda3\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1)
Requirement already satisfied: jinja2 in C:\Users\mohdk\anaconda3\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in C:\Users\mohdk\anaconda3\Lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in C:\Users\mohdk\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.3)
Requirement already satisfied: joblib>=1.1.1 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn->sentence-transformers) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn->sentence-transformers) (2.2.0)
Requirement already satisfied: click>=8.2.1 in C:\Users\mohdk\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.3.5)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\mohdk\anaconda3\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in C:\Users\mohdk\anaconda3\Lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.0)
Downloading sentence_transformers-5.2.3-py3-none-any.whl (494 kB)
Downloading transformers-5.3.0-py3-none-any.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   --- ------------------------------------ 1.0/10.7 MB 6.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/10.7 MB 6.9 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/10.7 MB 7.0 MB/s eta 0:00:01
   -------------------- ------------------- 5.5/10.7 MB 7.0 MB/s eta 0:00:01
   ------------------------- -------------- 6.8/10.7 MB 6.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.7 MB 7.1 MB/s eta 0:00:01
   -------------------------------------- - 10.2/10.7 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 6.9 MB/s  0:00:01
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Installing collected packages: safetensors, tokenizers, transformers, sentence-transformers

   ---------------------------------------- 0/4 [safetensors]
   ---------- ----------------------------- 1/4 [tokenizers]
   ---------- ----------------------------- 1/4 [tokenizers]
   ---------- ----------------------------- 1/4 [tokenizers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]
   -------------------- ------------------- 2/4 [transformers]

In [116]:
from sentence_transformers import SentenceTransformer

In [117]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\mohdk\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:129: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\mohdk\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [118]:
texts = pilot_df["clean_body"].tolist()

embeddings = model.encode(
    texts,
    batch_size=64,
    show_progress_bar=True
)

print("Embedding shape:", embeddings.shape)

Batches:   0%|          | 0/285 [00:00<?, ?it/s]

Embedding shape: (18186, 384)

In [119]:
embeddings.shape

(18186, 384)

In [120]:
import numpy as np

np.save("../outputs/pilot_embeddings.npy", embeddings)
pilot_df.to_csv("../data/processed/pilot_cleaned_emails.csv", index=False)

print("Saved embeddings to ../outputs/pilot_embeddings.npy")
print("Saved pilot dataset to ../data/processed/pilot_cleaned_emails.csv")

Saved embeddings to ../outputs/pilot_embeddings.npy
Saved pilot dataset to ../data/processed/pilot_cleaned_emails.csv

In [121]:
!pip install hdbscan umap-learn scikit-learn

Collecting hdbscan

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mohdk\anaconda3\Lib\site-packages\~klearn'.
  You can safely remove it manually.

  Downloading hdbscan-0.8.41-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting umap-learn
  Downloading umap_learn-0.5.11-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: scikit-learn in C:\Users\mohdk\anaconda3\Lib\site-packages (1.2.2)
Requirement already satisfied: numpy<3,>=1.20 in C:\Users\mohdk\anaconda3\Lib\site-packages (from hdbscan) (1.26.4)
Requirement already satisfied: scipy>=1.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from hdbscan) (1.11.4)
Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: joblib>=1.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from hdbscan) (1.2.0)
Requirement already satisfied: numba>=0.51.2 in C:\Users\mohdk\anaconda3\Lib\site-packages (from umap-learn) (0.59.0)
Collecting pynndescent>=0.5 (from umap-learn)
  Downloading pynndescent-0.6.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: tqdm in C:\Users\mohdk\anaconda3\Lib\site-packages (from umap-learn) (4.67.3)
Collecting joblib>=1.0 (from hdbscan)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: llvmlite<0.43,>=0.42.0dev0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from numba>=0.51.2->umap-learn) (0.42.0)
Requirement already satisfied: colorama in C:\Users\mohdk\anaconda3\Lib\site-packages (from tqdm->umap-learn) (0.4.6)
Downloading hdbscan-0.8.41-cp311-cp311-win_amd64.whl (687 kB)
   ---------------------------------------- 0.0/687.1 kB ? eta -:--:--
   ------------------------------ --------- 524.3/687.1 kB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 687.1/687.1 kB 2.1 MB/s  0:00:00
Downloading umap_learn-0.5.11-py3-none-any.whl (90 kB)
Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 2.4 MB/s eta 0:00:04
   ---------- ----------------------------- 2.1/8.1 MB 5.3 MB/s eta 0:00:02
   ---------------- ----------------------- 3.4/8.1 MB 5.6 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.1 MB 6.5 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.1 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 6.3 MB/s  0:00:01
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading pynndescent-0.6.0-py3-none-any.whl (73 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn, pynndescent, hdbscan, umap-learn

  Attempting uninstall: threadpoolctl

    Found existing installation: threadpoolctl 2.2.0

    Uninstalling threadpoolctl-2.2.0:

   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
      Successfully uninstalled threadpoolctl-2.2.0
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
  Attempting uninstall: joblib
   ---------------------------------------- 0/6 [threadpoolctl]
    Found existing installation: joblib 1.2.0
   ---------------------------------------- 0/6 [threadpoolctl]
   ------ --------------------------------- 1/6 [joblib]
   ------ --------------------------------- 1/6 [joblib]
    Uninstalling joblib-1.2.0:
   ------ --------------------------------- 1/6 [joblib]
   ------ --------------------------------- 1/6 [joblib]
      Successfully uninstalled joblib-1.2.0
   ------ --------------------------------- 1/6 [joblib]
   ------ --------------------------------- 1/6 [joblib]
   ------ --------------------------------- 1/6 [joblib]

In [123]:
import hdbscan
import umap

AttributeError: module 'sklearn.metrics._dist_metrics' has no attribute 'DistanceMetric64'

In [124]:
!pip uninstall -y scikit-learn sklearn

Found existing installation: scikit-learn 1.8.0
Uninstalling scikit-learn-1.8.0:
  Successfully uninstalled scikit-learn-1.8.0

WARNING: Failed to remove contents in a temporary directory 'C:\Users\mohdk\anaconda3\Lib\site-packages\~-learn'.
You can safely remove it manually.
WARNING: Skipping sklearn as it is not installed.

In [125]:
!pip install scikit-learn==1.5.2

Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp311-cp311-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (1.11.4)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (3.6.0)
Downloading scikit_learn-1.5.2-cp311-cp311-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/11.0 MB 3.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/11.0 MB 3.4 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.0 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.0 MB 2.5 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.0 MB 2.1 MB/s eta 0:00:05
   ----------- ---------------------------- 3.1/11.0 MB 2.2 MB/s eta 0:00:04
   ------------------ --------------------- 5.0/11.0 MB 2.9 MB/s eta 0:00:03
   ------------------------- -------------- 7.1/11.0 MB 3.7 MB/s eta 0:00:02
   -------------------------------- ------- 8.9/11.0 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.0 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 4.6 MB/s  0:00:02
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.5.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.

In [126]:
!pip install --force-reinstall hdbscan

Collecting hdbscan
  Using cached hdbscan-0.8.41-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting numpy<3,>=1.20 (from hdbscan)
  Downloading numpy-2.4.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting scipy>=1.0 (from hdbscan)
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn>=1.6 (from hdbscan)
  Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting joblib>=1.0 (from hdbscan)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn>=1.6->hdbscan)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached hdbscan-0.8.41-cp311-cp311-win_amd64.whl (687 kB)
Downloading numpy-2.4.2-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.6/12.6 MB 7.6 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.6 MB 8.7 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 9.3 MB/s eta 0:00:01
   ------------------------ --------------- 7.9/12.6 MB 9.4 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 9.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 8.0 MB/s  0:00:01
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   - -------------------------------------- 1.3/36.6 MB 5.6 MB/s eta 0:00:07
   --- ------------------------------------ 3.1/36.6 MB 7.4 MB/s eta 0:00:05
   ----- ---------------------------------- 5.0/36.6 MB 7.9 MB/s eta 0:00:04
   ------- -------------------------------- 7.1/36.6 MB 8.2 MB/s eta 0:00:04
   --------- ------------------------------ 8.9/36.6 MB 8.4 MB/s eta 0:00:04
   ------------ --------------------------- 11.0/36.6 MB 8.6 MB/s eta 0:00:03
   -------------- ------------------------- 13.1/36.6 MB 8.7 MB/s eta 0:00:03
   ---------------- ----------------------- 14.9/36.6 MB 8.8 MB/s eta 0:00:03
   ------------------ --------------------- 17.0/36.6 MB 8.9 MB/s eta 0:00:03
   -------------------- ------------------- 19.1/36.6 MB 8.9 MB/s eta 0:00:02
   ---------------------- ----------------- 20.7/36.6 MB 8.8 MB/s eta 0:00:02
   ------------------------ --------------- 22.3/36.6 MB 8.7 MB/s eta 0:00:02
   -------------------------- ------------- 24.1/36.6 MB 8.6 MB/s eta 0:00:02
   ---------------------------- ----------- 26.0/36.6 MB 8.6 MB/s eta 0:00:02
   ------------------------------ --------- 27.5/36.6 MB 8.6 MB/s eta 0:00:02
   -------------------------------- ------- 29.4/36.6 MB 8.5 MB/s eta 0:00:01
   ---------------------------------- ----- 31.5/36.6 MB 8.6 MB/s eta 0:00:01
   ----------------------------------- ---- 32.5/36.6 MB 8.5 MB/s eta 0:00:01
   ------------------------------------ --- 33.8/36.6 MB 8.3 MB/s eta 0:00:01
   -------------------------------------- - 34.9/36.6 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.6 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 7.5 MB/s  0:00:04
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, numpy, joblib, scipy, scikit-learn, hdbscan

  Attempting uninstall: threadpoolctl

    Found existing installation: threadpoolctl 3.6.0

    Uninstalling threadpoolctl-3.6.0:

   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
      Successfully uninstalled threadpoolctl-3.6.0
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
  Attempting uninstall: numpy
   ---------------------------------------- 0/6 [threadpoolctl]
    Found existing installation: numpy 1.26.4
   ---------------------------------------- 0/6 [threadpoolctl]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
    Uninstalling numpy-1.26.4:
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mohdk\AppData\Local\Temp\pip-uninstall-c7izj_xu'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mohdk\anaconda3\Lib\site-packages\~cipy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.4.2 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.2 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.4.2 which is incompatible.
numba 0.59.0 requires numpy<1.27,>=1.22, but you have numpy 2.4.2 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.2 which is incompatible.
tensorflow-intel 2.16.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.4.2 which is incompatible.

   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
      Successfully uninstalled scipy-1.11.4
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
   -------------------- ------------------- 3/6 [scipy]
  Attempting uninstall: scikit-learn
   -------------------- ------------------- 3/6 [scipy]
   -------------------------- ------------- 4/6 [scikit-learn]
    Found existing installation: scikit-learn 1.5.2
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
    Uninstalling scikit-learn-1.5.2:
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
      Successfully uninstalled scikit-learn-1.5.2
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]
   -------------------------- ------------- 4/6 [scikit-learn]

In [127]:
import sklearn
print("scikit-learn version:", sklearn.__version__)

import hdbscan
import umap

print("hdbscan imported successfully")
print("umap imported successfully")

scikit-learn version: 1.2.2

AttributeError: module 'sklearn.metrics._dist_metrics' has no attribute 'DistanceMetric64'

In [1]:
!pip install scikit-learn==1.5.2

Collecting scikit-learn==1.5.2
  Using cached scikit_learn-1.5.2-cp311-cp311-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (2.4.2)
Requirement already satisfied: scipy>=1.6.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (1.17.1)
Requirement already satisfied: joblib>=1.2.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in C:\Users\mohdk\anaconda3\Lib\site-packages (from scikit-learn==1.5.2) (3.6.0)
Using cached scikit_learn-1.5.2-cp311-cp311-win_amd64.whl (11.0 MB)
Installing collected packages: scikit-learn
Successfully installed scikit-learn-1.5.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.

In [2]:
!pip install --force-reinstall scikit-learn==1.6.1
!pip install --force-reinstall hdbscan umap-learn

Collecting scikit-learn==1.6.1
  Downloading scikit_learn-1.6.1-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting numpy>=1.19.5 (from scikit-learn==1.6.1)
  Using cached numpy-2.4.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting scipy>=1.6.0 (from scikit-learn==1.6.1)
  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn==1.6.1)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn==1.6.1)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp311-cp311-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/11.1 MB 10.5 MB/s eta 0:00:01
   ---------- ----------------------------- 2.9/11.1 MB 7.3 MB/s eta 0:00:02
   ----------------- ---------------------- 5.0/11.1 MB 8.2 MB/s eta 0:00:01
   ------------------------- -------------- 7.1/11.1 MB 8.6 MB/s eta 0:00:01
   --------------------------------- ------ 9.4/11.1 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 8.4 MB/s  0:00:01
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached numpy-2.4.2-cp311-cp311-win_amd64.whl (12.6 MB)
Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, numpy, joblib, scipy, scikit-learn

  Attempting uninstall: threadpoolctl

    Found existing installation: threadpoolctl 3.6.0

    Uninstalling threadpoolctl-3.6.0:

   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]
   ---------------------------------------- 0/5 [threadpoolctl]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mohdk\anaconda3\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\mohdk\AppData\Local\Temp\pip-uninstall-2bg49o_4'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.4.2 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.2 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.4.2 which is incompatible.
numba 0.59.0 requires numpy<1.27,>=1.22, but you have numpy 2.4.2 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.2 which is incompatible.
tensorflow-intel 2.16.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.4.2 which is incompatible.

Collecting hdbscan
  Using cached hdbscan-0.8.41-cp311-cp311-win_amd64.whl.metadata (15 kB)
Collecting umap-learn
  Using cached umap_learn-0.5.11-py3-none-any.whl.metadata (26 kB)
Collecting numpy<3,>=1.20 (from hdbscan)
  Using cached numpy-2.4.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting scipy>=1.0 (from hdbscan)
  Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn>=1.6 (from hdbscan)
  Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting joblib>=1.0 (from hdbscan)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting numba>=0.51.2 (from umap-learn)
  Downloading numba-0.64.0-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Collecting pynndescent>=0.5 (from umap-learn)
  Using cached pynndescent-0.6.0-py3-none-any.whl.metadata (6.9 kB)
Collecting tqdm (from umap-learn)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting llvmlite<0.47,>=0.46.0dev0 (from numba>=0.51.2->umap-learn)
  Downloading llvmlite-0.46.0-cp311-cp311-win_amd64.whl.metadata (4.9 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn>=1.6->hdbscan)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting colorama (from tqdm->umap-learn)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Using cached hdbscan-0.8.41-cp311-cp311-win_amd64.whl (687 kB)
Using cached numpy-2.4.2-cp311-cp311-win_amd64.whl (12.6 MB)
Using cached umap_learn-0.5.11-py3-none-any.whl (90 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading numba-0.64.0-cp311-cp311-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.7 MB 4.8 MB/s eta 0:00:01
   -------------------------- ------------- 1.8/2.7 MB 3.6 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 3.1 MB/s  0:00:00
Downloading llvmlite-0.46.0-cp311-cp311-win_amd64.whl (38.1 MB)
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   - -------------------------------------- 1.6/38.1 MB 6.5 MB/s eta 0:00:06
   --- ------------------------------------ 3.1/38.1 MB 6.6 MB/s eta 0:00:06
   ---- ----------------------------------- 4.7/38.1 MB 6.6 MB/s eta 0:00:06
   ----- ---------------------------------- 5.5/38.1 MB 5.9 MB/s eta 0:00:06
   ------- -------------------------------- 6.8/38.1 MB 6.1 MB/s eta 0:00:06
   -------- ------------------------------- 8.4/38.1 MB 6.1 MB/s eta 0:00:05
   ---------- ----------------------------- 9.7/38.1 MB 6.0 MB/s eta 0:00:05
   ----------- ---------------------------- 11.3/38.1 MB 6.2 MB/s eta 0:00:05
   ------------ --------------------------- 12.3/38.1 MB 6.0 MB/s eta 0:00:05
   -------------- ------------------------- 13.9/38.1 MB 6.2 MB/s eta 0:00:04
   --------------- ------------------------ 15.2/38.1 MB 6.2 MB/s eta 0:00:04
   ----------------- ---------------------- 16.8/38.1 MB 6.2 MB/s eta 0:00:04
   ------------------- -------------------- 18.4/38.1 MB 6.3 MB/s eta 0:00:04
   -------------------- ------------------- 19.7/38.1 MB 6.3 MB/s eta 0:00:03
   ---------------------- ----------------- 21.2/38.1 MB 6.4 MB/s eta 0:00:03
   ----------------------- ---------------- 22.5/38.1 MB 6.4 MB/s eta 0:00:03
   ------------------------- -------------- 24.1/38.1 MB 6.4 MB/s eta 0:00:03
   -------------------------- ------------- 25.7/38.1 MB 6.5 MB/s eta 0:00:02
   ---------------------------- ----------- 27.3/38.1 MB 6.5 MB/s eta 0:00:02
   ----------------------------- ---------- 28.3/38.1 MB 6.5 MB/s eta 0:00:02
   ------------------------------ --------- 29.4/38.1 MB 6.3 MB/s eta 0:00:02
   ------------------------------- -------- 30.4/38.1 MB 6.3 MB/s eta 0:00:02
   --------------------------------- ------ 32.0/38.1 MB 6.3 MB/s eta 0:00:01
   ---------------------------------- ----- 33.3/38.1 MB 6.3 MB/s eta 0:00:01
   ------------------------------------ --- 34.9/38.1 MB 6.3 MB/s eta 0:00:01
   -------------------------------------- - 36.7/38.1 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------  38.0/38.1 MB 6.4 MB/s eta 0:00:01
   ---------------------------------------- 38.1/38.1 MB 6.1 MB/s  0:00:06
Using cached pynndescent-0.6.0-py3-none-any.whl (73 kB)
Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
Using cached scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: threadpoolctl, numpy, llvmlite, joblib, colorama, tqdm, scipy, numba, scikit-learn, pynndescent, hdbscan, umap-learn

  Attempting uninstall: threadpoolctl

    Found existing installation: threadpoolctl 3.6.0

    Uninstalling threadpoolctl-3.6.0:

   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]
   ----------------------------------------  0/12 [threadpoolctl]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.0 requires FuzzyTM>=0.4.0, which is not installed.
astropy 5.3.4 requires numpy<2,>=1.21, but you have numpy 2.4.2 which is incompatible.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.2 which is incompatible.
matplotlib 3.8.0 requires numpy<2,>=1.21, but you have numpy 2.4.2 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.2 which is incompatible.
tensorflow-intel 2.16.1 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.4.2 which is incompatible.

   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
   --- ------------------------------------  1/12 [numpy]
  Attempting uninstall: llvmlite
   --- ------------------------------------  1/12 [numpy]
    Found existing installation: llvmlite 0.42.0
   --- ------------------------------------  1/12 [numpy]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
    Uninstalling llvmlite-0.42.0:
   ------ ---------------------------------  2/12 [llvmlite]
      Successfully uninstalled llvmlite-0.42.0
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
   ------ ---------------------------------  2/12 [llvmlite]
  Attempting uninstall: joblib
   ------ ---------------------------------  2/12 [llvmlite]
   ---------- -----------------------------  3/12 [joblib]
    Found existing installation: joblib 1.5.3
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
    Uninstalling joblib-1.5.3:
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
      Successfully uninstalled joblib-1.5.3
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
   ---------- -----------------------------  3/12 [joblib]
  Attempting uninstall: colorama
   ---------- -----------------------------  3/12 [joblib]
   ------------- --------------------------  4/12 [colorama]
    Found existing installation: colorama 0.4.6
   ------------- --------------------------  4/12 [colorama]
    Uninstalling colorama-0.4.6:
   ------------- --------------------------  4/12 [colorama]
      Successfully uninstalled colorama-0.4.6
   ------------- --------------------------  4/12 [colorama]
   ------------- --------------------------  4/12 [colorama]
   ------------- --------------------------  4/12 [colorama]
   ------------- --------------------------  4/12 [colorama]
   ------------- --------------------------  4/12 [colorama]
  Attempting uninstall: tqdm
   ------------- --------------------------  4/12 [colorama]
    Found existing installation: tqdm 4.67.3
   ------------- --------------------------  4/12 [colorama]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
    Uninstalling tqdm-4.67.3:
   ---------------- -----------------------  5/12 [tqdm]
      Successfully uninstalled tqdm-4.67.3
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
   ---------------- -----------------------  5/12 [tqdm]
  Attempting uninstall: scipy
   ---------------- -----------------------  5/12 [tqdm]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
    Found existing installation: scipy 1.17.1
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
    Uninstalling scipy-1.17.1:
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]
   -------------------- -------------------  6/12 [scipy]

In [3]:
import sklearn
print("scikit-learn version:", sklearn.__version__)

import hdbscan
import umap

print("hdbscan imported successfully")
print("umap imported successfully")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mohdk\AppData\Local\Temp\ipykernel_137932\2750166055.py", line 1, in <module>
    import sklearn
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\__init__.py", line 70, in <module>
    from sklearn.base import clone  # noqa: E402
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\base.py", line 19, in <module>
    from sklearn.utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\__init__.py", line 9, in <module>
    from sklearn.utils._chunking import gen_batches, gen_even_slices
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\_chunking.py", line 11, in <module>
    from sklearn.utils._param_validation import Interval, validate_params
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 17, in <module>
    from sklearn.utils.validation import _is_arraylike_not_scalar
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 24, in <module>
    from sklearn.utils._array_api import (
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py", line 20, in <module>
    from sklearn.utils.fixes import parse_version
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\fixes.py", line 19, in <module>
    import pandas as pd
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 50, in <module>
    from pandas.core import (
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\ops\__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\ops\array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\mohdk\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mohdk\AppData\Local\Temp\ipykernel_137932\2750166055.py", line 1, in <module>
    import sklearn
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\__init__.py", line 70, in <module>
    from sklearn.base import clone  # noqa: E402
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\base.py", line 19, in <module>
    from sklearn.utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\__init__.py", line 9, in <module>
    from sklearn.utils._chunking import gen_batches, gen_even_slices
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\_chunking.py", line 11, in <module>
    from sklearn.utils._param_validation import Interval, validate_params
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 17, in <module>
    from sklearn.utils.validation import _is_arraylike_not_scalar
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 24, in <module>
    from sklearn.utils._array_api import (
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py", line 20, in <module>
    from sklearn.utils.fixes import parse_version
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\sklearn\utils\fixes.py", line 19, in <module>
    import pandas as pd
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\arrays\arrow\array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py", line 60, in <module>
    from pandas.core import (
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\core\nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\Users\mohdk\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

scikit-learn version: 1.8.0

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mohdk\AppData\Local\Temp\ipykernel_137932\2750166055.py", line 5, in <module>
    import umap
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\umap\__init__.py", line 7, in <module>
    from .parametric_umap import ParametricUMAP, load_ParametricUMAP
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\umap\parametric_umap.py", line 13, in <module>
    import tensorflow as tf
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\framework\ops.py", line 46, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\pywrap_tfe.py", line 25, in <module>
    from tensorflow.python._pywrap_tfe import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mohdk\AppData\Local\Temp\ipykernel_137932\2750166055.py", line 5, in <module>
    import umap
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\umap\__init__.py", line 7, in <module>
    from .parametric_umap import ParametricUMAP, load_ParametricUMAP
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\umap\parametric_umap.py", line 13, in <module>
    import tensorflow as tf
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\framework\ops.py", line 49, in <module>
    from tensorflow.python.client import pywrap_tf_session
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\client\pywrap_tf_session.py", line 19, in <module>
    from tensorflow.python.client._pywrap_tf_session import *

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Users\mohdk\anaconda3\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\mohdk\AppData\Local\Temp\ipykernel_137932\2750166055.py", line 5, in <module>
    import umap
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\umap\__init__.py", line 7, in <module>
    from .parametric_umap import ParametricUMAP, load_ParametricUMAP
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\umap\parametric_umap.py", line 13, in <module>
    import tensorflow as tf
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from tensorflow._api.v2 import __internal__
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\_api\v2\__internal__\__init__.py", line 8, in <module>
    from tensorflow._api.v2.__internal__ import autograph
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\_api\v2\__internal__\autograph\__init__.py", line 8, in <module>
    from tensorflow.python.autograph.core.ag_ctx import control_status_ctx # line: 34
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\core\ag_ctx.py", line 21, in <module>
    from tensorflow.python.autograph.utils import ag_logging
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\utils\__init__.py", line 17, in <module>
    from tensorflow.python.autograph.utils.context_managers import control_dependency_on_returns
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\autograph\utils\context_managers.py", line 19, in <module>
    from tensorflow.python.framework import ops
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\framework\ops.py", line 50, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\eager\context.py", line 37, in <module>
    from tensorflow.python.eager import execute
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\eager\execute.py", line 21, in <module>
    from tensorflow.python.framework import dtypes
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\tensorflow\python\framework\dtypes.py", line 21, in <module>
    import ml_dtypes
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ml_dtypes\__init__.py", line 32, in <module>
    from ml_dtypes._finfo import finfo
  File "C:\Users\mohdk\anaconda3\Lib\site-packages\ml_dtypes\_finfo.py", line 19, in <module>
    from ml_dtypes._ml_dtypes_ext import bfloat16

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

hdbscan imported successfully
umap imported successfully

In [2]:
import pandas as pd
import numpy as np

pilot_df = pd.read_csv("../data/processed/pilot_cleaned_emails.csv")
embeddings = np.load("../outputs/pilot_embeddings.npy")

print("Dataset shape:", pilot_df.shape)
print("Embeddings shape:", embeddings.shape)

Dataset shape: (18186, 11)
Embeddings shape: (18186, 384)

In [3]:
print("Dataset shape:", pilot_df.shape)
print("Embeddings shape:", embeddings.shape)

Dataset shape: (18186, 11)
Embeddings shape: (18186, 384)

In [4]:
import umap

umap_model = umap.UMAP(
    n_neighbors=15,
    n_components=15,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

reduced_embeddings = umap_model.fit_transform(embeddings)

print("Reduced embedding shape:", reduced_embeddings.shape)

C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Reduced embedding shape: (18186, 15)

In [5]:
print(reduced_embeddings.shape)

(18186, 15)

In [9]:
import hdbscan

clusterer = hdbscan.HDBSCAN(
    min_cluster_size=15,
    metric="euclidean",
    cluster_selection_method="eom"
)

clusters = clusterer.fit_predict(reduced_embeddings)

print("Number of clusters found:", len(set(clusters)) - (1 if -1 in clusters else 0))
print("Number of noise points:", list(clusters).count(-1))

Number of clusters found: 157
Number of noise points: 10461

In [10]:
pilot_df["cluster"] = clusters
pilot_df["cluster"].value_counts().head(10)

cluster
-1      10461
 149      332
 98       213
 103      207
 131      196
 142      155
 117      151
 39       148
 31       147
 138      145
Name: count, dtype: int64

In [8]:
pilot_df["cluster"].value_counts().head(10)

cluster
-1     11415
 61      454
 62      296
 10      254
 27      231
 65      229
 56      223
 64      216
 55      182
 69      172
Name: count, dtype: int64

In [11]:
cluster_sizes = pilot_df["cluster"].value_counts()

cluster_sizes.describe()

count      158.000000
mean       115.101266
std        829.499559
min         15.000000
25%         23.000000
50%         32.500000
75%         59.750000
max      10461.000000
Name: count, dtype: float64

In [12]:
cluster_sizes.head(20)

cluster
-1      10461
 149      332
 98       213
 103      207
 131      196
 142      155
 117      151
 39       148
 31       147
 138      145
 115      144
 10       122
 151      117
 79       107
 81       103
 132      101
 70        94
 156       93
 95        92
 153       91
Name: count, dtype: int64

In [13]:
(cluster_sizes[cluster_sizes < 30]).count()

71

In [14]:
def show_cluster_examples(cluster_id, n=5):
    examples = pilot_df[pilot_df["cluster"] == cluster_id]["clean_body"].sample(n, random_state=42)
    print(f"\nCluster {cluster_id} examples:\n")
    for i, text in enumerate(examples, 1):
        print(f"{i}. {text[:300]}...\n")

In [15]:
show_cluster_examples(149)
show_cluster_examples(98)
show_cluster_examples(103)
show_cluster_examples(131)
show_cluster_examples(142)

Cluster 149 examples:

1. Pete-- Congratulations on your new baby girl. Girls are a lot of TROUBLE so prepare!!! I hope that your wife is doing well. I'll make sure to come by your desk to see pictures! Purvi...

2. we are going to new orleans sat and set sail sun. for this summer i might go home for a weekend and to vegas for a bachelor party. you?...

3. I'm glad you had a good weekend. I am taking DK out to dinner tonght so I won't be home. Dad "Caron Horton" <Caron.Horton@Trinity.edu> on 04/30/2001 09:07:10 AM...

4. No one would notice if I forgot my bras!!!! Thanks for the well wishes. I'll take lots of pictures so you can see them. I can't wait for this week to be over...only one and a half days!! Robin...

5. Boy did I flake on the happy hour. Jeff-I think I've gone over THE edge. Hectic does't even work anymore. I'm on a (fairly)good project at HP..IN SACRAMENTO, in fact 20 miles north of Sacramento. I LOVE the company, the learning, the work, the teams, the people, the career opportunities. I hate the ...


Cluster 98 examples:

1. On the various matters currently before the California PUC: The Commission order stating that the utilities should absorb any difference between DWR's cost of power and the retail rate freeze is still technically in effect. (The order only applies, however, to the power purchased under the Governor'...

2. For your information: Vince Kaminski passed on to me the following California-related presentations delivered at a recent conference he attended (Energy and Power Risk Management, 5/14-5/15, Houston). Please let me know if you would like a copy of any of these: *Roach, Craig (Boston Pacific Company,...

3. Here is a link to the governor's press release. He is billing it as 5,000 MW of contracts, but then he says that there is only 500 available immediately. WIth the remainder available from 3 to 10 years. http://www.governor.ca.gov/state/govsite/gov_htmldisplay.jsp?BV_SessionID=@@@@ 1673762879.0981503...

4. Daniel: Attached is the research I did on components of residential electricity rates for select states (CA, MA, NY and PA). As discussed, once you have reviewed it, please forward it on. Please let me know if you have any questions or if you require additional information. Jennifer 713-345-3550...

5. EXECUTIVE SUMMARY CPUC Terminates Direct Access PG&E/SoCal Bankruptcy Developments Direct Access Despite the information that a CPUC representative responded favorably to a vote-delay request sent by the state's major business interests, and pressure to delay the vote from Governor Davis, the CPUC e...


Cluster 103 examples:

1. Mike, Please, help him. Only publicly available data (exchanges, etc.) Vince...

2. Shirley, FYI Vince...

3. Kristin This is another member of the Tiger Team I am ready to take as an intern. We shall have enough work for all of them. Vince...

4. Jeff, The meeting is scheduled for Wednesday afternoon. Vince...

5. Paul, We shall invite both of them for an interview. Vince...


Cluster 131 examples:

1. Hi! I'll sign the agreement. Orjan...

2. Christian asked me to work with Dan Watkiss to prepare a FERC filing to terminate EPMI's participation in the PX. I have asked Dan to get started as Christian said we may decide to file as soon as today. See attached explanation. Does EES also have a participation agreement? And if so do we also nee...

3. Tana: I've already spoken with Clem this morning and he is on board with this form. The changes we are making are not substantive so let's make 'em (marked in yellow on the hard copy I've delivered to you) and get this signed right away. Clem is going on vacation Friday. We should also email a copy ...

4. This should be so much easier; Foti is not cooperating so I am having to spend time hunting down his Co. # and RC #, which hopefully Estalee will be able to provide. I reiterate my position that lawyers are not the ones who should have to do this. Rest assured I'll follow through on this one and Lia...

5. Mark, I apologise for the delay. The developers were travelling and I had to literally chase them to get a response. It appears that we do not have business relationships with the entities listed by you. No MOU or Non- Disclosure Agreements have been signed although there are discussions going on wi...


Cluster 142 examples:

1. Mark - Mike Robison and I have finalized the form of GTC's for ECFC and are forwarding them to you for further distribution. Thanks. John - The only modifications to ECFC's online GTC's are as follows: Contract Formation In order to maintain consistency with the other product lines online GTCs, we'v...

2. We have received an executed Master Agreement: Type of Contract: ISDA Master Agreement (Multicurrency-Cross Border) Effective Date: December 20, 2000 Enron Entity: Risk Management & Trading Corp. Counterparty: ENA Upstream Company, LLC Transactions Covered: Approved for all products with the excepti...

3. Not sure yet. We will be talking with AReM and will want your input. We may have to file but not sure. Jim...

4. Jane: Happy New Year back! Hope you are looking forward to a great 2001. After re-reading the string of emails, I am pleased to tell you that real help has arrived. We have just added three new lawyers to our group and Carol St. Clair has just returned from maternity leave. Carol will handle the cre...

5. Rod: You may recall that we spoke about upgrading the old Master Energy Price Swap to an ISDA. Can you please send a new credit worksheet? If you are not handling, please let me know who to nag. Thanks. Sara...

In [16]:
cluster_representatives = (
    pilot_df.groupby("cluster")["clean_body"]
    .first()
    .reset_index()
)

cluster_representatives.head()

   cluster                                         clean_body
0       -1  Due to the current business circumstances the ...
1        0  RIGZONE DAILY NEWS -- THURSDAY, JANUARY 10, 20...
2        1  This is a reminder of Enron's Email retention ...
3        2  Sent from my BlackBerry Wireless Handheld (www...
4        3  Gentlemen, Here's the PCB log.? Something is w...

In [17]:
cluster_summary = (
    pilot_df.groupby("cluster")
    .size()
    .reset_index(name="email_count")
    .sort_values("email_count", ascending=False)
)

cluster_summary.head(10)

     cluster  email_count
0         -1        10461
150      149          332
99        98          213
104      103          207
132      131          196
143      142          155
118      117          151
40        39          148
32        31          147
139      138          145

In [18]:
cluster_summary = cluster_summary.merge(
    cluster_representatives,
    on="cluster"
)

cluster_summary.head(10)

   cluster  email_count                                         clean_body
0       -1        10461  Due to the current business circumstances the ...
1      149          332  Hi there, Just a note to say hello. Hello. Nit...
2       98          213  It's hard to formulate a position without more...
3      103          207  Let's meet at 4:00. Vince J Kaminski 06/01/200...
4      131          196  See attached - I put Karl's few nit comments i...
5      142          155  Just to confirm recent conversations: 1) At th...
6      117          151  Didn't the deal that Victor extended cover the...
7       39          148  This is to remind all employees that, as earli...
8       31          147  Dear Friend , Congratulations! You've been pre...
9      138          145  Would you take Terry Glenn and Charlie Garner ...

In [25]:
cluster_summary.head(10)

,cluster,email_count,clean_body_x,clean_body_y
0,149,332,"Hi there, Just a note to say hello. Hello. Nit...",Pete-- Congratulations on your new baby girl. ...
1,98,213,It's hard to formulate a position without more...,On the various matters currently before the Ca...
2,103,207,Let's meet at 4:00. Vince J Kaminski 06/01/200...,"Mike, Please, help him. Only publicly availabl..."
3,131,196,See attached - I put Karl's few nit comments i...,Hi! I'll sign the agreement. Orjan Christian a...
4,142,155,Just to confirm recent conversations: 1) At th...,Mark - Mike Robison and I have finalized the f...
5,117,151,Didn't the deal that Victor extended cover the...,Check these deals: 70422 92754 I have a proble...
6,39,148,"This is to remind all employees that, as earli...",Rick: Please find attached a short memo regard...
7,31,147,"Dear Friend , Congratulations! You've been pre...",Get one of the HOTTEST Phones on the Market!! ...
8,138,145,Would you take Terry Glenn and Charlie Garner ...,This in an automated e-mail sent out from the ...
9,115,144,"Kevin, Thanks a lot. Vince Kevin G Moore 10/26...",You are bad to the bones...! Bob Bowen 04/25/2...

In [20]:
cluster_summary = cluster_summary[cluster_summary["cluster"] != -1]
cluster_summary.head(10)

    cluster  email_count                                         clean_body
1       149          332  Hi there, Just a note to say hello. Hello. Nit...
2        98          213  It's hard to formulate a position without more...
3       103          207  Let's meet at 4:00. Vince J Kaminski 06/01/200...
4       131          196  See attached - I put Karl's few nit comments i...
5       142          155  Just to confirm recent conversations: 1) At th...
6       117          151  Didn't the deal that Victor extended cover the...
7        39          148  This is to remind all employees that, as earli...
8        31          147  Dear Friend , Congratulations! You've been pre...
9       138          145  Would you take Terry Glenn and Charlie Garner ...
10      115          144  Kevin, Thanks a lot. Vince Kevin G Moore 10/26...

In [21]:
cluster_summary = cluster_summary.sort_values("email_count", ascending=False)
cluster_summary.head(10)

    cluster  email_count                                         clean_body
1       149          332  Hi there, Just a note to say hello. Hello. Nit...
2        98          213  It's hard to formulate a position without more...
3       103          207  Let's meet at 4:00. Vince J Kaminski 06/01/200...
4       131          196  See attached - I put Karl's few nit comments i...
5       142          155  Just to confirm recent conversations: 1) At th...
6       117          151  Didn't the deal that Victor extended cover the...
7        39          148  This is to remind all employees that, as earli...
8        31          147  Dear Friend , Congratulations! You've been pre...
9       138          145  Would you take Terry Glenn and Charlie Garner ...
10      115          144  Kevin, Thanks a lot. Vince Kevin G Moore 10/26...

In [22]:
cluster_samples = (
    pilot_df.groupby("cluster")["clean_body"]
    .apply(lambda x: " ".join(x.sample(min(5, len(x)), random_state=42)))
    .reset_index()
)

cluster_samples.head()

   cluster                                         clean_body
0       -1  Question is whether DWR steps up and/or ISO's ...
1        0  Thank you for your request. You will be notifi...
2        1  This is a reminder of Enron's Email retention ...
3        2  Shelley, I just found out this message did not...
4        3  (See attached file: HPLN1230.xls) (See attache...

In [23]:
cluster_summary = cluster_summary.merge(cluster_samples, on="cluster")
cluster_summary.head()

,cluster,email_count,clean_body_x,clean_body_y
0,149,332,"Hi there, Just a note to say hello. Hello. Nit...",Pete-- Congratulations on your new baby girl. ...
1,98,213,It's hard to formulate a position without more...,On the various matters currently before the Ca...
2,103,207,Let's meet at 4:00. Vince J Kaminski 06/01/200...,"Mike, Please, help him. Only publicly availabl..."
3,131,196,See attached - I put Karl's few nit comments i...,Hi! I'll sign the agreement. Orjan Christian a...
4,142,155,Just to confirm recent conversations: 1) At th...,Mark - Mike Robison and I have finalized the f...

In [26]:
cluster_summary.head(10)

,cluster,email_count,clean_body_x,clean_body_y
0,149,332,"Hi there, Just a note to say hello. Hello. Nit...",Pete-- Congratulations on your new baby girl. ...
1,98,213,It's hard to formulate a position without more...,On the various matters currently before the Ca...
2,103,207,Let's meet at 4:00. Vince J Kaminski 06/01/200...,"Mike, Please, help him. Only publicly availabl..."
3,131,196,See attached - I put Karl's few nit comments i...,Hi! I'll sign the agreement. Orjan Christian a...
4,142,155,Just to confirm recent conversations: 1) At th...,Mark - Mike Robison and I have finalized the f...
5,117,151,Didn't the deal that Victor extended cover the...,Check these deals: 70422 92754 I have a proble...
6,39,148,"This is to remind all employees that, as earli...",Rick: Please find attached a short memo regard...
7,31,147,"Dear Friend , Congratulations! You've been pre...",Get one of the HOTTEST Phones on the Market!! ...
8,138,145,Would you take Terry Glenn and Charlie Garner ...,This in an automated e-mail sent out from the ...
9,115,144,"Kevin, Thanks a lot. Vince Kevin G Moore 10/26...",You are bad to the bones...! Bob Bowen 04/25/2...

In [27]:
cluster_summary = cluster_summary.rename(
    columns={
        "clean_body_x": "example_email",
        "clean_body_y": "cluster_sample"
    }
)

cluster_summary = cluster_summary[["cluster", "email_count", "example_email", "cluster_sample"]]

cluster_summary.head(10)

,cluster,email_count,example_email,cluster_sample
0,149,332,"Hi there, Just a note to say hello. Hello. Nit...",Pete-- Congratulations on your new baby girl. ...
1,98,213,It's hard to formulate a position without more...,On the various matters currently before the Ca...
2,103,207,Let's meet at 4:00. Vince J Kaminski 06/01/200...,"Mike, Please, help him. Only publicly availabl..."
3,131,196,See attached - I put Karl's few nit comments i...,Hi! I'll sign the agreement. Orjan Christian a...
4,142,155,Just to confirm recent conversations: 1) At th...,Mark - Mike Robison and I have finalized the f...
5,117,151,Didn't the deal that Victor extended cover the...,Check these deals: 70422 92754 I have a proble...
6,39,148,"This is to remind all employees that, as earli...",Rick: Please find attached a short memo regard...
7,31,147,"Dear Friend , Congratulations! You've been pre...",Get one of the HOTTEST Phones on the Market!! ...
8,138,145,Would you take Terry Glenn and Charlie Garner ...,This in an automated e-mail sent out from the ...
9,115,144,"Kevin, Thanks a lot. Vince Kevin G Moore 10/26...",You are bad to the bones...! Bob Bowen 04/25/2...

In [28]:
cluster_summary.shape

(157, 4)

In [29]:
cluster_summary_filtered = cluster_summary[cluster_summary["email_count"] >= 50]

print("Clusters before:", cluster_summary.shape[0])
print("Clusters after filtering:", cluster_summary_filtered.shape[0])

cluster_summary_filtered.head(10)

Clusters before: 157
Clusters after filtering: 48

,cluster,email_count,example_email,cluster_sample
0,149,332,"Hi there, Just a note to say hello. Hello. Nit...",Pete-- Congratulations on your new baby girl. ...
1,98,213,It's hard to formulate a position without more...,On the various matters currently before the Ca...
2,103,207,Let's meet at 4:00. Vince J Kaminski 06/01/200...,"Mike, Please, help him. Only publicly availabl..."
3,131,196,See attached - I put Karl's few nit comments i...,Hi! I'll sign the agreement. Orjan Christian a...
4,142,155,Just to confirm recent conversations: 1) At th...,Mark - Mike Robison and I have finalized the f...
5,117,151,Didn't the deal that Victor extended cover the...,Check these deals: 70422 92754 I have a proble...
6,39,148,"This is to remind all employees that, as earli...",Rick: Please find attached a short memo regard...
7,31,147,"Dear Friend , Congratulations! You've been pre...",Get one of the HOTTEST Phones on the Market!! ...
8,138,145,Would you take Terry Glenn and Charlie Garner ...,This in an automated e-mail sent out from the ...
9,115,144,"Kevin, Thanks a lot. Vince Kevin G Moore 10/26...",You are bad to the bones...! Bob Bowen 04/25/2...

In [30]:
cluster_summary_filtered["cluster_text"] = cluster_summary_filtered["cluster_sample"].apply(
    lambda x: x[:2000]
)

cluster_summary_filtered.head()

,cluster,email_count,example_email,cluster_sample,cluster_text
0,149,332,"Hi there, Just a note to say hello. Hello. Nit...",Pete-- Congratulations on your new baby girl. ...,Pete-- Congratulations on your new baby girl. ...
1,98,213,It's hard to formulate a position without more...,On the various matters currently before the Ca...,On the various matters currently before the Ca...
2,103,207,Let's meet at 4:00. Vince J Kaminski 06/01/200...,"Mike, Please, help him. Only publicly availabl...","Mike, Please, help him. Only publicly availabl..."
3,131,196,See attached - I put Karl's few nit comments i...,Hi! I'll sign the agreement. Orjan Christian a...,Hi! I'll sign the agreement. Orjan Christian a...
4,142,155,Just to confirm recent conversations: 1) At th...,Mark - Mike Robison and I have finalized the f...,Mark - Mike Robison and I have finalized the f...

In [33]:
def generate_theme_label(text):

    prompt = f"""
You are analyzing internal corporate email conversations.

Based on the following email samples, identify the main communication theme.

Return ONLY a short theme label (3–6 words).

Emails:
{text}
"""

    response = llm.invoke(prompt)
    return response.content.strip()

In [35]:
cluster_texts = cluster_summary_filtered["cluster_text"].tolist()

In [36]:
len(cluster_texts)

48

In [37]:
from langchain_community.chat_models import ChatOllama

llm = ChatOllama(model="llama3")

ModuleNotFoundError: No module named 'langchain_community'

In [38]:
pip install langchain-community

Collecting langchain-community
  Using cached langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-core<2.0.0,>=1.0.1 (from langchain-community)
  Downloading langchain_core-1.2.17-py3-none-any.whl.metadata (4.4 kB)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.2-py3-none-any.whl.metadata (4.8 kB)
Collecting SQLAlchemy<3.0.0,>=1.4.0 (from langchain-community)
  Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-community) (6.0.3)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community)
  Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-community)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Using cached dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Using cached pydantic_settings-2.13.1-py3-none-any.whl.metadata (3.4 kB)
Collecting langsmith<1.0.0,>=0.1.125 (from langchain-community)
  Downloading langsmith-0.7.14-py3-none-any.whl.metadata (15 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Using cached httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=1.26.2 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-community) (1.26.4)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community)
  Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Using cached marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Using cached langchain_text_splitters-1.1.1-py3-none-any.whl.metadata (3.3 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Using cached pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core<2.0.0,>=1.0.1->langchain-community)
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (4.15.0)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.0.1->langchain-community)
  Using cached uuid_utils-0.14.1-cp39-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain-community) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Collecting orjson>=3.9.14 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading orjson-3.11.7-cp311-cp311-win_amd64.whl.metadata (43 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting xxhash>=3.0.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Using cached xxhash-3.6.0-cp311-cp311-win_amd64.whl.metadata (13 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.1.125->langchain-community)
  Downloading zstandard-0.25.0-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
Requirement already satisfied: anyio in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: certifi in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: idna in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading pydantic_core-2.41.5-cp311-cp311-win_amd64.whl.metadata (7.4 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain-community)
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.6.3)
Collecting greenlet>=1 (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community)
  Downloading greenlet-3.3.2-cp311-cp311-win_amd64.whl.metadata (3.8 kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Using cached mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Using cached langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl (457 kB)
Using cached dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Using cached httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.2-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   -------------------- ------------------- 0.5/1.0 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 1.0/1.0 MB 2.9 MB/s  0:00:00
Downloading langchain_core-1.2.17-py3-none-any.whl (502 kB)
Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Using cached langchain_text_splitters-1.1.1-py3-none-any.whl (35 kB)
Downloading langsmith-0.7.14-py3-none-any.whl (347 kB)
Using cached marshmallow-3.26.2-py3-none-any.whl (50 kB)
Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Using cached pydantic-2.12.5-py3-none-any.whl (463 kB)
Downloading pydantic_core-2.41.5-cp311-cp311-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.0 MB ? eta -:--:--
   -------------------------- ------------- 1.3/2.0 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 3.9 MB/s  0:00:00
Using cached pydantic_settings-2.13.1-py3-none-any.whl (58 kB)
Downloading sqlalchemy-2.0.48-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----------------------------- ---------- 1.6/2.1 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 5.5 MB/s  0:00:00
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Using cached uuid_utils-0.14.1-cp39-abi3-win_amd64.whl (187 kB)
Downloading yarl-1.23.0-cp311-cp311-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Downloading greenlet-3.3.2-cp311-cp311-win_amd64.whl (230 kB)
Using cached mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading orjson-3.11.7-cp311-cp311-win_amd64.whl (124 kB)
Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Using cached python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached xxhash-3.6.0-cp311-cp311-win_amd64.whl (31 kB)
Downloading zstandard-0.25.0-cp311-cp311-win_amd64.whl (506 kB)
Installing collected packages: zstandard, xxhash, uuid-utils, typing-inspection, tenacity, python-dotenv, pydantic-core, propcache, orjson, mypy-extensions, multidict, marshmallow, jsonpatch, httpx-sse, greenlet, frozenlist, annotated-types, aiohappyeyeballs, yarl, typing-inspect, SQLAlchemy, requests-toolbelt, pydantic, aiosignal, pydantic-settings, langsmith, dataclasses-json, aiohttp, langchain-core, langchain-text-splitters, langchain-classic, langchain-community

   ----------------------------------------  0/32 [zstandard]
   -- -------------------------------------  2/32 [uuid-utils]
   --- ------------------------------------  3/32 [typing-inspection]
   ----- ----------------------------------  4/32 [tenacity]
   ----- ----------------------------------  4/32 [tenacity]
   ------ ---------------------------------  5/32 [python-dotenv]
   ------ ---------------------------------  5/32 [python-dotenv]
   ------- --------------------------------  6/32 [pydantic-core]
   -------- -------------------------------  7/32 [propcache]
   ---------- -----------------------------  8/32 [orjson]
   ------------ --------------------------- 10/32 [multidict]
   ------------- -------------------------- 11/32 [marshmallow]
   ------------- -------------------------- 11/32 [marshmallow]
   ------------- -------------------------- 11/32 [marshmallow]
   --------------- ------------------------ 12/32 [jsonpatch]
   ---------------- ----------------------- 13/32 [httpx-sse]
   ---------------- ----------------------- 13/32 [httpx-sse]
   ----------------- ---------------------- 14/32 [greenlet]
   ----------------- ---------------------- 14/32 [greenlet]
   ----------------- ---------------------- 14/32 [greenlet]
   ----------------- ---------------------- 14/32 [greenlet]
   ----------------- ---------------------- 14/32 [greenlet]
   ----------------- ---------------------- 14/32 [greenlet]
   ------------------ --------------------- 15/32 [frozenlist]
   -------------------- ------------------- 16/32 [annotated-types]
   --------------------- ------------------ 17/32 [aiohappyeyeballs]
   ---------------------- ----------------- 18/32 [yarl]
   ---------------------- ----------------- 18/32 [yarl]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   ------------------------- -------------- 20/32 [SQLAlchemy]
   -------------------------- ------------- 21/32 [requests-toolbelt]
   -------------------------- ------------- 21/32 [requests-toolbelt]
   -------------------------- ------------- 21/32 [requests-toolbelt]
   -------------------------- ------------- 21/32 [requests-toolbelt]
   -------------------------- ------------- 21/32 [requests-toolbelt]
   -------------------------- ------------- 21/32 [requests-toolbelt]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   --------------------------- ------------ 22/32 [pydantic]
   ---------------------------- ----------- 23/32 [aiosignal]
   ---------------------------- ----------- 23/32 [aiosignal]
   ------------------------------ --------- 24/32 [pydantic-settings]
   ------------------------------ --------- 24/32 [pydantic-settings]
   ------------------------------ --------- 24/32 [pydantic-settings]
   ------------------------------ --------- 24/32 [pydantic-settings]
   ------------------------------ --------- 24/32 [pydantic-settings]
   ------------------------------ --------- 24/32 [pydantic-settings]
   ------------------------------ --------- 24/32 [pydantic-settings]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   ------------------------------- -------- 25/32 [langsmith]
   -------------------------------- ------- 26/32 [dataclasses-json]
   -------------------------------- ------- 26/32 [dataclasses-json]
   --------------------------------- ------ 27/32 [aiohttp]
   --------------------------------- ------ 27/32 [aiohttp]

In [ ]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4o-mini")

In [39]:
pip install langchain-openai

Collecting langchain-openai
  Using cached langchain_openai-1.1.10-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.13 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-openai) (1.2.17)
Collecting openai<3.0.0,>=2.20.0 (from langchain-openai)
  Downloading openai-2.26.0-py3-none-any.whl.metadata (29 kB)
Collecting tiktoken<1.0.0,>=0.7.0 (from langchain-openai)
  Downloading tiktoken-0.12.0-cp311-cp311-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.7.14)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.25.0)
Requirement already satisfied: anyio in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (4.12.1)
Requirement already satisfied: certifi in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (1.0.9)
Requirement already satisfied: idna in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.16.0)
Collecting distro<2,>=1.7.0 (from openai<3.0.0,>=2.20.0->langchain-openai)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting jiter<1,>=0.10.0 (from openai<3.0.0,>=2.20.0->langchain-openai)
  Downloading jiter-0.13.0-cp311-cp311-win_amd64.whl.metadata (5.3 kB)
Collecting sniffio (from openai<3.0.0,>=2.20.0->langchain-openai)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>4 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from openai<3.0.0,>=2.20.0->langchain-openai) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.4.2)
Requirement already satisfied: regex>=2022.1.18 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2026.2.28)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (2.6.3)
Requirement already satisfied: colorama in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from tqdm>4->openai<3.0.0,>=2.20.0->langchain-openai) (0.4.6)
Using cached langchain_openai-1.1.10-py3-none-any.whl (87 kB)
Downloading openai-2.26.0-py3-none-any.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ------------------ --------------------- 0.5/1.1 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 1.1/1.1 MB 3.1 MB/s  0:00:00
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading jiter-0.13.0-cp311-cp311-win_amd64.whl (204 kB)
Downloading tiktoken-0.12.0-cp311-cp311-win_amd64.whl (879 kB)
   ---------------------------------------- 0.0/879.4 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/879.4 kB ? eta -:--:--
   ---------------------------------------- 879.4/879.4 kB 3.0 MB/s  0:00:00
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: sniffio, jiter, distro, tiktoken, openai, langchain-openai

   ---------------------------------------- 0/6 [sniffio]
   ------------- -------------------------- 2/6 [distro]
   -------------------- ------------------- 3/6 [tiktoken]
   -------------------- ------------------- 3/6 [tiktoken]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   -------------------------- ------------- 4/6 [openai]
   --------------------------------- ------ 5/6 [langchain-openai]
   --------------------------------- ------ 5/6 [langchain-openai]
   --------------------------------- ------ 5/6 [langchain-openai]
   --------------------------------- ------ 5/6 [langchain-openai]
   ---------------------------------------- 6/6 [langchain-openai]

Successfully installed distro-1.9.0 jiter-0.13.0 langchain-openai-1.1.10 openai-2.26.0 sniffio-1.3.1 tiktoken-0.12.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
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

In [41]:
import os
os.environ["OPENAI_API_KEY"] = "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"

In [42]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    model="gpt-4o-mini",
    temperature=0
)

In [45]:
!pip install -U langchain-ollama

Collecting langchain-ollama
  Downloading langchain_ollama-1.0.1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-ollama) (1.2.17)
Collecting ollama<1.0.0,>=0.6.0 (from langchain-ollama)
  Downloading ollama-0.6.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.14)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: anyio in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2026.2.25)
Requirement already satisfied: httpcore==1.* in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11)
Requirement already satisfied: h11>=0.16 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.4.5)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\mohdk\anaconda3\envs\ai_comms\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.6.3)
Downloading langchain_ollama-1.0.1-py3-none-any.whl (29 kB)
Downloading ollama-0.6.1-py3-none-any.whl (14 kB)
Installing collected packages: ollama, langchain-ollama

   ---------------------------------------- 0/2 [ollama]
   -------------------- ------------------- 1/2 [langchain-ollama]
   ---------------------------------------- 2/2 [langchain-ollama]

Successfully installed langchain-ollama-1.0.1 ollama-0.6.1

In [46]:
from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="llama3.1:8b",
    temperature=0
)

In [47]:
response = llm.invoke("Return only a 3 to 5 word label for emails about meeting scheduling and coordination.")
print(response.content)

Here are some options:

* Meeting Schedule Update
* Coordination Request Sent
* Scheduling Follow Up Needed
* Meeting Time Confirmation Required
* Schedule Coordination Complete

In [48]:
response = llm.invoke("""
You are labeling email clusters.

Return EXACTLY ONE theme label.

Rules:
- 3 to 5 words only
- no bullet points
- no explanations
- no multiple options

Topic: emails about meeting scheduling and coordination.
""")

print(response.content)

Meeting Schedule Coordination

In [49]:
cluster_summary_filtered["cluster_text"] = (
    cluster_summary_filtered["cluster_sample"].str.slice(0, 800)
)

In [54]:
def generate_theme_label(text):

    prompt = f"""
You are labeling clusters of corporate email conversations.

Goal:
Identify the GENERAL category of communication across the emails.

Important:
Do NOT use specific names, organizations, or document titles.

Return a GENERAL communication category.

Rules:
- EXACTLY ONE label
- 3 to 5 words only
- Use a GENERAL business communication topic
- Do NOT include names or organizations
- Do NOT include acronyms like FERC, PUC, etc
- Do NOT include specific documents
- No punctuation
- No explanations

Good labels:
Personal Social Communication
Regulatory Policy Discussion
Meeting Scheduling Coordination
Legal Document Review
Contract Negotiation Discussion
Internal Announcement Updates
Project Status Coordination

Bad labels:
FERC Filing Update
California PUC Orders
Congratulations to Pete
GTC Modifications Review
Internship Opportunities

Emails:
{text}
"""

    response = llm.invoke(prompt)
    return response.content.strip()

In [55]:
test_df = cluster_summary_filtered.head(5).copy()

test_df["theme"] = test_df["cluster_text"].apply(generate_theme_label)

test_df[["cluster", "email_count", "theme"]]

   cluster  email_count                            theme
0      149          332    Personal Social Communication
1       98          213     Regulatory Policy Discussion
2      103          207    Internal Announcement Updates
3      131          196  Contract Negotiation Discussion
4      142          155  Contract Negotiation Discussion

In [56]:
cluster_summary_filtered["theme"] = (
    cluster_summary_filtered["cluster_text"]
    .apply(generate_theme_label)
)

In [57]:
cluster_summary_filtered[["theme","email_count"]].sort_values(
    "email_count",
    ascending=False
).head(20)

                                   theme  email_count
0          Personal Social Communication          332
1           Regulatory Policy Discussion          213
2          Internal Announcement Updates          207
3        Contract Negotiation Discussion          196
4        Contract Negotiation Discussion          155
5        Contract Negotiation Discussion          151
6           Regulatory Policy Discussion          148
7               Spam Marketing Promotion          147
8        Meeting Scheduling Coordination          145
9          Personal Social Communication          144
10         Network Infrastructure Update          122
11          Regulatory Policy Discussion          117
12           Project Status Coordination          107
13       Meeting Scheduling Coordination          103
14       Contract Negotiation Discussion          101
15       Contract Negotiation Discussion           94
16       Meeting Scheduling Coordination           93
17  Personal Contact Information Sharing           92
18       Meeting Scheduling Coordination           91
19         Internal Announcement Updates           88

In [58]:
theme_summary = (
    cluster_summary_filtered
    .groupby("theme")["email_count"]
    .sum()
    .reset_index()
    .sort_values("email_count", ascending=False)
)

theme_summary

                                   theme  email_count
2        Meeting Scheduling Coordination         1032
0        Contract Negotiation Discussion          807
10          Regulatory Policy Discussion          704
7          Personal Social Communication          682
1          Internal Announcement Updates          553
8            Project Status Coordination          284
12              Spam Marketing Promotion          147
3          Network Infrastructure Update          122
6   Personal Contact Information Sharing           92
9     Public Relations Crisis Management           69
4     Organizational Change Announcement           66
11             Security Approval Process           59
5      Personal Communication Discussion           51

In [59]:
total_emails = pilot_df.shape[0]

theme_summary["percentage"] = (
    theme_summary["email_count"] / total_emails * 100
).round(2)

theme_summary

                                   theme  email_count  percentage
2        Meeting Scheduling Coordination         1032        5.67
0        Contract Negotiation Discussion          807        4.44
10          Regulatory Policy Discussion          704        3.87
7          Personal Social Communication          682        3.75
1          Internal Announcement Updates          553        3.04
8            Project Status Coordination          284        1.56
12              Spam Marketing Promotion          147        0.81
3          Network Infrastructure Update          122        0.67
6   Personal Contact Information Sharing           92        0.51
9     Public Relations Crisis Management           69        0.38
4     Organizational Change Announcement           66        0.36
11             Security Approval Process           59        0.32
5      Personal Communication Discussion           51        0.28

In [60]:
theme_summary.to_csv("../data/processed/theme_summary.csv", index=False)

In [61]:
cluster_explorer = cluster_summary_filtered[
    ["cluster", "theme", "email_count", "example_email"]
]

cluster_explorer.to_csv("../data/processed/cluster_explorer.csv", index=False)

In [62]:
email_dataset = pilot_df.merge(
    cluster_summary_filtered[["cluster", "theme"]],
    on="cluster",
    how="left"
)

email_dataset.to_csv("../data/processed/email_theme_dataset.csv", index=False)

In [63]:
theme_examples = (
    email_dataset
    .groupby("theme")["clean_body"]
    .first()
    .reset_index()
)

theme_examples.to_csv("../data/processed/theme_examples.csv", index=False)

In [64]:
email_dataset.head()

,file,sender,recipients,date,subject,body,body_length,clean_body,relevance_label,alpha_ratio,word_count,cluster,theme
0,saibi-e/inbox/846.,no.address@enron.com,NaN,"Fri, 7 Dec 2001 11:53:41 -0800 (PST)","New Operating Hours for the Energizer Cafe, Th...",Due to the current business circumstances the ...,372,Due to the current business circumstances the ...,keep,0.687845,66,-1,NaN
1,shapiro-r/discussion_threads/554.,leslie.lawner@enron.com,"richard.shapiro@enron.com, james.steffes@enron...","Wed, 16 May 2001 09:37:00 -0700 (PDT)",Latest FERC data request,"Randy, Becky and I just had a conference call ...",1178,"Randy, Becky and I just had a conference call ...",keep,0.796713,209,-1,NaN
2,white-s/deleted_items/735.,fran.chang@enron.com,"fran.chang@enron.com, heather.dunton@enron.com...","Mon, 22 Oct 2001 15:45:38 -0700 (PDT)",ERV Notification: (Power West Price Off-Peak ...,The report named: Power West Price Off-Peak <h...,317,The report named: Power West Price Off-Peak <h...,keep,0.705696,22,74,Internal Announcement Updates
3,perlingiere-d/sent/2289.,debra.perlingiere@enron.com,mklein@flgas.com,"Wed, 21 Mar 2001 06:31:00 -0800 (PST)",Re: GISB contract info,Debra Perlingiere\nEnron North America Corp.\n...,689,Debra Perlingiere Enron North America Corp. Le...,keep,0.617284,21,151,Regulatory Policy Discussion
4,mann-k/discussion_threads/3440.,roseann.engeldorf@enron.com,kay.mann@enron.com,"Fri, 20 Apr 2001 07:48:00 -0700 (PDT)",NW A&A,See attached - I put Karl's few nit comments i...,198,See attached - I put Karl's few nit comments i...,keep,0.750000,39,131,Contract Negotiation Discussion

In [65]:
email_dataset["theme"] = email_dataset["theme"].fillna("Other Communication")

In [66]:
sender_theme = (
    email_dataset
    .groupby(["sender","theme"])
    .size()
    .reset_index(name="email_count")
)

sender_theme.to_csv("../data/processed/sender_theme_distribution.csv", index=False)

In [68]:
email_dataset["date"] = pd.to_datetime(
    email_dataset["date"],
    errors="coerce",
    utc=True
)

email_dataset["month"] = email_dataset["date"].dt.to_period("M")

C:\Users\mohdk\AppData\Local\Temp\ipykernel_219148\278294114.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  email_dataset["date"] = pd.to_datetime(
C:\Users\mohdk\AppData\Local\Temp\ipykernel_219148\278294114.py:7: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  email_dataset["month"] = email_dataset["date"].dt.to_period("M")

In [69]:
email_dataset[["date","month"]].head()

                       date    month
0 2001-12-07 19:53:41+00:00  2001-12
1 2001-05-16 16:37:00+00:00  2001-05
2 2001-10-22 22:45:38+00:00  2001-10
3 2001-03-21 14:31:00+00:00  2001-03
4 2001-04-20 14:48:00+00:00  2001-04

In [70]:
theme_timeline = (
    email_dataset
    .groupby(["month","theme"])
    .size()
    .reset_index(name="email_count")
)

theme_timeline.to_csv("../data/processed/theme_timeline.csv", index=False)

In [71]:
print("Unique themes:", email_dataset["theme"].nunique())
print("Total emails:", email_dataset.shape[0])

Unique themes: 14
Total emails: 18186

In [74]:
final_dataset = email_dataset[
    [
        "sender",
        "recipients",
        "date",
        "month",
        "subject",
        "clean_body",
        "cluster",
        "theme"
    ]
]

final_dataset.to_parquet("../data/processed/email_dataset.parquet")

ArrowKeyError: No type extension with name arrow.py_extension_type found

In [73]:
pip install pyarrow

Collecting pyarrow
  Using cached pyarrow-23.0.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Using cached pyarrow-23.0.1-cp311-cp311-win_amd64.whl (27.5 MB)
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.1
Note: you may need to restart the kernel to use updated packages.

In [75]:
final_dataset = email_dataset[
    [
        "sender",
        "recipients",
        "date",
        "month",
        "subject",
        "clean_body",
        "cluster",
        "theme"
    ]
].copy()

final_dataset["month"] = final_dataset["month"].astype(str)

In [76]:
final_dataset.to_parquet("../data/processed/email_dataset.parquet", index=False)

ArrowKeyError: A type extension with name pandas.period already defined